# Definição de variáveis (ambiente “local” do REST Client)
@base_url = https://vigilant-space-goldfish-x5xg6ggxx7g7c9p45-8080.app.github.dev

### 1. Criar novo usuário
POST {{base_url}}/api/usuarios
Content-Type: application/json

{
  "username": "kamila",
  "password": "kamila123"
}

###

### 2. Listar todos os usuários
GET {{base_url}}/api/usuarios
Accept: application/json

###

### 3. Buscar usuário por ID
GET {{base_url}}/api/usuarios/1
Accept: application/json

###

### 4. Atualizar usuário (PUT)
PUT {{base_url}}/api/usuarios/1
Content-Type: application/json

{
  "username": "joaonovo",
  "password": "novaSenha456"
}

###

### 5. Remover usuário (DELETE)
DELETE {{base_url}}/api/usuarios/1
Accept: */*
